apiVersion: apps/v1
kind: Deployment
metadata:
  name: techno-app
  labels:
    app: techno-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techno-app
  template:
    metadata:
      labels:
        app: techno-app
    spec:
      containers:
      - name: techno-app
        image: 975050210074.dkr.ecr.us-east-1.amazonaws.com/techno-ecr-kotasemarang-jabriel:latest
        ports:
        - containerPort: 2000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: $AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          value: $AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          value: $AWS_SESSION_TOKEN
        - name: AWS_REGION
          value: $AWS_REGION
        - name: ATHENA_DB
          value: $ATHENA_DB
        - name: S3_STAGING_DIR
          value: $S3_STAGING_DIR
        - name: FLASK_SECRET_KEY
          value: lks
        - name: API_GATEWAY_URL
          value: $API_GATEWAY_URL
        - name: SNS_TOPIC_ARN
          value: $SNS_TOPIC_ARN
        - name: ATHENA_SCHEMA_NAME
          value: $ATHENA_SCHEMA_NAME